module.exports = {
    logLevel: process.env.LOG_LEVEL || 'info',
    serial: process.env.SERIAL || '/dev/ttyAMA0',
    baudRate: process.env.BAUD_RATE || 38400,
    deviceMapping: process.env.DEVICE_MAPPING || 'RPICT7V1.json',
    precision: process.env.PRECISION || 2,
    absoluteValues: process.env.ABSOLUTE_VALUES || false,
    sensorValueThreshold: process.env.SENSOR_VALUE_THRESHOLD || 0,
    mqttUrl: process.env.MQTT_URL || 'mqtt://localhost:1883',
    mqttUser: process.env.MQTT_USER,
    mqttPassword: process.env.MQTT_PASSWORD,
    mqttBaseTopic: process.env.MQTT_BASE_TOPIC || 'rpict',
    hassDiscovery: process.env.HASS_DISCOVERY ? process.env.HASS_DISCOVERY.toLowerCase() === 'true' : true,
    hassDiscoveryPrefix: process.env.HASS_DISCOVERY_PREFIX || 'homeassistant',
};
